### ISSUE TITLE
Basic blocks starting with "jmp" instruction cause errors in REIL cfg

### ISSUE THREAD

**Issue by montyly** [google/binnavi#100]
Hi,

I encountered a bug during the creation of the REIL cfg.

When a basic block starts with a "jmp" instruction followed by other instructions, BinNavi creates two REIL basic blocks; yet it fails to create the appropriate edge between them.

As minimal example, the following code :

``` asm
; nasm -f elf test.asm 
; ld -s -o test test.o
section     .text
global      _start                              

_start:                                       
    jmp label
label:    
    ret
```

Creates this x86 basic block:
<img src="https://cloud.githubusercontent.com/assets/13798342/17649988/a56e62da-6241-11e6-89b9-228a99bb7748.png" width="200">

Which is translated into two REIL basic blocks:
![reil](https://cloud.githubusercontent.com/assets/13798342/17649991/add6b486-6241-11e6-99e7-0cd84b01b217.png)

However, the edge father -> son is missing.

Best,
Josselin

(tested on version 356eaa8)

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
