### ISSUE TITLE
Possible defect (parts of the expression are identical)

### ISSUE THREAD

**Issue by AppChecker** [google/binnavi#101]
Hi!

We've checked your project with AppChecker static analyzer (https://npo-echelon.ru/en/solutions/appchecker.php) and found a couple of possible defects.
1) In [src/main/java/com/google/security/zynamics/binnavi/disassembly/CNaviViewEdge.java#L89](https://github.com/google/binnavi/blob/356eaa86278dcda5f976e7166937a6bc729a22c2/src/main/java/com/google/security/zynamics/binnavi/disassembly/CNaviViewEdge.java#L89)
```
 if ((getSource() instanceof IAddressNode) && (getSource() instanceof IAddressNode)) {
...
}
```
getSource() is checked twice. maybe getTargen() should be checked like it's done in https://github.com/google/binnavi/blob/356eaa86278dcda5f976e7166937a6bc729a22c2/src/main/java/com/google/security/zynamics/binnavi/disassembly/CNaviViewEdge.java#L103

2) The same thiing is in https://github.com/google/binnavi/blob/356eaa86278dcda5f976e7166937a6bc729a22c2/src/main/java/com/google/security/zynamics/binnavi/disassembly/CNaviEdge.java#L89

All possible defects were found by Echelon team with [AppChecker static analyzer](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
