### ISSUE TITLE
Object comparison always returns true.

### ISSUE THREAD

**Issue by lifove** [google/binnavi#102]
I've found a code smell and a possibly bug in a recent snapshot.
Path: src/main/java/com/google/security/zynamics/binnavi/disassembly/CFunction.java

```java
439   @Override
440   public boolean inSameDatabase(final SQLProvider provider) {
441     return provider.equals(provider);
442   }
```

As Line 441 always return true, should it be, this.provider.equals(provider)?
```java
439   @Override
440   public boolean inSameDatabase(final SQLProvider provider) {
441     return this.provider.equals(provider);
442   }
```

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
