### ISSUE TITLE
Question about typical approach to invoke binnavi jar package from standalone application

### ISSUE THREAD

**Issue by computereasy** [google/binnavi#103]
Dear all,

Sorry if this question is a little bit off-topic. I am trying to leverage `REIL` and the CFG maintained by `binnavi` to do some binary code analysis. 

Right now, I am able to import the IDA-Pro output into the db, boot `binnavi` to load data from the db, and use its interactive interface to go through the disassembled output. 

Generally speaking, what I am thinking to do is like this (suppose I am using `Java`):

    import com.google.security.zynamics.binnavi.API.XXX
    import com.google.security.zynamics.binnavi.API.YYY
    ....

    val dis = load_bin_data("test_bin_data_in_db")  
    val func_list = parse_into_functions(dis)
    val cfg = func_list.get_cfg("foo")
    for (node in cfg.nodes)
    {
        translate_into_reil(node.instructions)
    }
   .....

Suppose binnavi has a bunch of APIs called `load_bin_data`; `parse_into_functions`; `get_cfg`....

However, by studying the provided [plugin](https://github.com/google/binnavi/blob/356eaa86278dcda5f976e7166937a6bc729a22c2/src/main/java/com/google/security/zynamics/binnavi/scripts/mono/sample/sample.py), it seems that such plugin is used as one additional component of the `binnavi`... not a standalone code to invoke `binnavi API` from the very beginning.

So here is my question: can I somehow use `binnavi` in the above approach? Is there any example/tutorial to do so? Any suggestion is strongly appreciated! Thank you!

**Comment by thomasdullien** [comment]
Hey there,

there was some way to run BinNavi in headless mode, I will try to dig up if
I can still find how it works.

Cheers,
Thomas

2017-03-02 17:55 GMT+01:00 Shuai Wang <notifications@github.com>:

**Comment by thomasdullien** [comment]
Hey there,

so apparently there used to be a blogpost describing how it's done:
https://twitter.com/flxflx/status/184256467925344257

Will see if somebody still has it.

Cheers,
Thomas

2017-03-02 18:03 GMT+01:00 Thomas Dullien <thomas.dullien@googlemail.com>:

**Comment by computereasy** [comment]
@thomasdullien Thank you so much for this prompt reply!!! I will check the materials as well.

**Comment by thomasdullien** [comment]
Hey there,

a very very old, but possibly helpful post:

http://www.the-interweb.com/serendipity/index.php?/archives/123-An-unconnected-string-of-thoughts-about-BinNavi-2.1.html


2017-03-02 18:07 GMT+01:00 Shuai Wang <notifications@github.com>:

**Comment by computereasy** [comment]
Dear Tomas,

Thank you so much for this valuable information!

Actually, I am able to load the DB, module and iterate each functions inside my own Java code base just now. It isn't that difficult. I am essentially thinking to leverage `REIL`  to perform some binary code analysis. Seems a good start :)

For people who are looking for similar examples, please take a look at the code here: https://github.com/google/binnavi/blob/master/src/test/java/com/google/security/zynamics/binnavi/REIL/CPostgreSQLDatabaseTest.java

It should be very understandable.

Thanks again! 

Sincerely,
Shuai
