### ISSUE TITLE
Parent Node of each basic block in a function is all Empty

### ISSUE THREAD

**Issue by computereasy** [google/binnavi#104]
Hello,

I am using `BinNavi` to analyze a program binary which is compiled from a quick sort code. In particular, I am trying to detect `loops` in the `partition` function:

    int partition( int a[], int l, int r) {
       int pivot, i, j, t;
       pivot = a[l];
       i = l; j = r+1;
		
       while( 1)
      {
   	do ++i; while( a[i] <= pivot && i <= r );
   	do --j; while( a[j] > pivot );
   	if( i >= j ) break;
   	t = a[i]; a[i] = a[j]; a[j] = t;
       }
        t = a[l]; a[l] = a[j]; a[j] = t;
       return j;
    }

I tried to use the following code to get all the loops:

    import com.google.security.zynamics.binnavi.disassembly.INaviFunction
    import com.google.security.zynamics.zylib.types.graphs.GraphAlgorithms

    def detect_loop(rf: INaviFunction) = {
        val t = GraphAlgorithms.getGraphLoops(rf.getGraph)
     ...

However, I then got such error:

    Exception in thread "main" com.google.security.zynamics.zylib.types.graphs.algorithms.MalformedGraphException: Error: Can not calculate dominator trees for graphs with more than one entry node
	at com.google.security.zynamics.zylib.types.graphs.algorithms.LengauerTarjan.calculate(LengauerTarjan.java:140)
	at com.google.security.zynamics.zylib.types.graphs.algorithms.LengauerTarjan.calculate(LengauerTarjan.java:259)
	at com.google.security.zynamics.zylib.types.graphs.GraphAlgorithms.getBackEdges(GraphAlgorithms.java:197)
	at com.google.security.zynamics.zylib.types.graphs.GraphAlgorithms.getGraphLoops(GraphAlgorithms.java:247)

Actually from the GUI of `BinNavi`, the graph looks pretty normal:

![screen shot 2017-03-03 at 11 35 08 am](https://cloud.githubusercontent.com/assets/5838310/23559590/7c0d5128-0005-11e7-97e9-bb0c72cda6a3.png)

I then use the following code to print out a node if its parent node is empty:

      for (t <- rf.getGraph.getNodes()) {
       if (t.getParents().size() == 0) {
         println(t.getAddress)
         println(t.getParents)
       }
     }

To my surprise, all the node in this function CFG have **empty** parent node, which seems inconsistent with the graph view.

    08048564
    []
    0804858D
    []
    080485A7
    []
    080485AF
    []
    080485C9
    []
    080485D1
     []
     080485D3
     []

So here is my question: am I doing anything wrong here?  By checking the `GUI`, `BinNavi` should have collected all the parent node information.. It's just somehow in the underlying code, such information is not avaliable...

Could anyone give me some help? Thank you!

**Comment by thomasdullien** [comment]
That looks like a bug in BinNavi. I will see, perhaps I can have a look
this weekend, if not, next monday.

2017-03-03 17:38 GMT+01:00 Shuai Wang <notifications@github.com>:

**Comment by computereasy** [comment]
@thomasdullien 

Thank you Tomas! Besides `getParents`, I also tried some other cases, for example `getOutgoingEdges`, `getChildren`.. 

They all return an empty list.

Do I actually need to explicitly `construct` the graph? 

High-levelly, here is what I am doing right now (the following code is written in `Scala`):

    m_database =
          new CDatabase("None", CJdbcDriverNames.jdbcPostgreSQLDriverName, "localhost", "binexport_test",
            "shuai", "123321", "test", false, false);

     m_database.connect()
     m_database.load()

     m = m_database.getContent.getModule(module_index)
     m.load()
     val fl = m.getContent.getFunctionContainer.getFunctions
   
      for (fr <- fl) {
        fr.load()
        if (fr.getName == "partition") {
            for (t <- fr.getGraph.getNodes()) {
                println(t.getAddress)
                println(t.getChildren)         // <---- all the output here is an empty list.
           }
        }
      }

**Comment by computereasy** [comment]
@thomasdullien  Hey Tomas, may I ask about whether you have fixed the bug? Thank you!

**Comment by thomasdullien** [comment]
Hey there,

sorry, haven't been able to look into it yet -- fell sick with the flu on
sunday, haven't been back at work.

2017-03-07 16:30 GMT+01:00 Shuai Wang <notifications@github.com>:

**Comment by computereasy** [comment]
@thomasdullien  I am sorry to hear about this.. Hope you get better soon :)

**Comment by thomasdullien** [comment]
Hey there,

just checking - I should be able to investigate wednesday. Or did the
mystery resolve itself?

Am 07.03.2017 4:33 PM schrieb "Thomas Dullien" <
thomas.dullien@googlemail.com>:
