### ISSUE TITLE
Reil code with `jcc` opcode when translating `sar` instructions

### ISSUE THREAD

**Issue by computereasy** [google/binnavi#105]
Hello,

when translating the following `x86` instruction:

      sar         eax, byte 1fh

`BinNavi` produces a large sequence of `Reil` instructions:

    0000000804843100: str [BYTE 31, EMPTY , BYTE t0]
    0000000804843101: str [DWORD eax, EMPTY , DWORD t1]
    0000000804843102: and [DWORD t1, DWORD 2147483648, DWORD t26]
    0000000804843103: bsh [DWORD t26, DWORD -31, DWORD t27]
    0000000804843104: sub [DWORD 0, DWORD t27, DWORD t28]
    0000000804843105: xor [DWORD t1, DWORD t28, DWORD t29]
    0000000804843106: sub [DWORD t29, DWORD t28, DWORD t30]
    0000000804843107: mod [BYTE t0, DWORD 32, DWORD t2]
    0000000804843108: bisz [DWORD t2, EMPTY , BYTE t3]
    0000000804843109: jcc [BYTE t3, EMPTY , ADDRESS 134513713.46]  <----
    000000080484310A: undef [EMPTY , EMPTY , BYTE AF]
    000000080484310B: sub [BYTE t2, BYTE 1, BYTE t20]
    000000080484310C: bsh [BYTE 1, BYTE t20, BYTE t23]
    000000080484310D: and [DWORD t1, BYTE t23, BYTE t24]
    000000080484310E: bisz [BYTE t24, EMPTY , BYTE t25]
    000000080484310F: xor [BYTE 1, BYTE t25, BYTE CF]
    0000000804843110: sub [DWORD 1, DWORD t2, DWORD t4]
    0000000804843111: bisz [DWORD t4, EMPTY , BYTE t5]
    0000000804843112: sub [DWORD 0, DWORD t2, DWORD t6]
    0000000804843113: and [BYTE 128, DWORD t1, BYTE t9]
    0000000804843114: bisz [BYTE t9, EMPTY , BYTE t10]
    0000000804843115: xor [BYTE 1, BYTE t10, BYTE t21]
    0000000804843116: bsh [DWORD 1, BYTE t2, DWORD t11]
    0000000804843117: div [DWORD t30, DWORD t11, DWORD t12]
    0000000804843118: sub [BYTE 0, BYTE t21, DWORD t13]
    0000000804843119: xor [DWORD t12, DWORD t13, DWORD t7]
    000000080484311A: jcc [BYTE t10, EMPTY , ADDRESS 134513713.35]  <----
    000000080484311B: add [DWORD t7, BYTE 1, DWORD t14]
    000000080484311C: bsh [BYTE 1, DWORD t2, DWORD t15]
    000000080484311D: sub [DWORD t15, BYTE 1, DWORD t16]
    000000080484311E: and [DWORD t1, DWORD t16, DWORD t17]
    000000080484311F: bisz [DWORD t17, EMPTY , BYTE t18]
    0000000804843120: xor [BYTE 1, BYTE t18, BYTE t19]
    0000000804843121: and [BYTE t21, BYTE t19, BYTE t22]
    0000000804843122: sub [DWORD t14, BYTE t22, DWORD t7]
    0000000804843123: and [WORD t7, BYTE 255, BYTE t8]
    0000000804843124: jcc [BYTE t3, EMPTY , ADDRESS 134513713.46]  <----
    0000000804843125: bisz [BYTE t10, EMPTY , BYTE SF]
    0000000804843126: bisz [BYTE t8, EMPTY , BYTE ZF]
    0000000804843127: jcc [BYTE t5, EMPTY , ADDRESS 134513713.41]  <----
    0000000804843128: str [BYTE 0, EMPTY , BYTE OF]
    0000000804843129: or [BYTE t5, BYTE t3, BYTE t31]
    000000080484312A: jcc [BYTE t31, EMPTY , ADDRESS 134513713.45]  <----
    000000080484312B: undef [EMPTY , EMPTY , BYTE OF]
    000000080484312C: jcc [BYTE 1, EMPTY , ADDRESS 134513713.46]  <----
    000000080484312D: str [BYTE 0, EMPTY , BYTE OF]
    000000080484312E: str [DWORD t7, EMPTY , DWORD eax]
    000000080484312F: nop [EMPTY , EMPTY , EMPTY ]

I am curious about the `jcc` instructions. Could anyone shed some lights on how should I interpret such opcode and what is the address (e.g., 134513713.45) ? Thank you!

**Comment by thomasdullien** [comment]
Hey there,

the reason for conditional jumps showing up in the translation is that the
REIL translation
may not have a simpler way to model the instruction (e.g. without
conditional branch). The
way to interpret the operand is as target address - although something
seems to be broken
here. Normally the 134513713.35 should mean the 35th REIL instruction
inside the translation of the instruction at 134513713 (normally the
current instruction).

000000080484311A: jcc [BYTE t10, EMPTY , ADDRESS 134513713.35]

Something is odd though - e.g. the addresses don't match. What is the
address
of the SAR instruction?

2017-03-12 21:11 GMT+01:00 Shuai Wang <notifications@github.com>:

**Comment by computereasy** [comment]
Hello Tomas, 

Thanks a lot for the information. The address of `sar` instruction is 0x08048431 (i.e., 134513713). It makes sense to me.

**Comment by computereasy** [comment]
Hi there,

I have to re-open this issue since something is still very confused to me. In the example shown in this issue, let's consider the following two `Reil` instructions:


    0000000804843109: jcc [BYTE t3, EMPTY , ADDRESS 134513713.46]  <----
    ....                                      <----- note that t7 is *ONLY* initialized here 
    000000080484312E: str [DWORD t7, EMPTY , DWORD eax]

If I am performing some data flow analysis for the above code, and by following the `true` branch of instruction at `0000000804843109`, I will directly go into instruction at `000000080484312E`. 

However, note that in the above case, `t7` is only initialized and modified in the `false` branch of the `jcc`. In other words, at the `true` branch of `jcc`, I actually have no idea what `t7` is.. 

Is there any specific reason that `BinNavi` is designed to do so? Thanks.

**Comment by thomasdullien** [comment]
Hey there,

that sounds like a bug to me. What was the original instruction from which
this was translated again?

Cheers,
Thomas

2017-03-21 16:16 GMT+01:00 Shuai Wang <notifications@github.com>:

**Comment by computereasy** [comment]
Hi @thomasdullien ,

The original instruction is:

    08048431   sar         eax, byte 1fh

**Comment by computereasy** [comment]
The whole set of the translated `reil` instruction is pasted in the first email.

**Comment by thomasdullien** [comment]
Hey there,

cool, thanks. Should be able to check it out today :)

Cheers,
Thomas

2017-03-21 16:25 GMT+01:00 Shuai Wang <notifications@github.com>:

**Comment by thomasdullien** [comment]
Hey there,

sorry, I havent gotten around to it yet. Is the issue still there?

Am 30.03.2017 10:13 schrieb "Shuai Wang" <notifications@github.com>:
