### ISSUE TITLE
excuse me, when i import idb file，a error will emerge

### ISSUE THREAD

**Issue by liuderui** [google/binnavi#112]
the bug message is that ...  (in binNavi)
The IDB file 'C:\Users\Administrator\Desktop\npp.7.5.8.Installer.x64.i64' could not be imported. Please check the stack trace for more information.

Possible causes:
  - Database connection problems.
  - Bug in the IDB exporter.

Problem impact:
  - The IDB file was imported partially. A raw module in an incosistent state was created. This raw module should be deleted.

and the bug message is that...(in cmd)
Reason: Could not start IDA Pro.
Importing project failed.
十二月 05, 2018 10:07:14 上午 com.google.security.zynamics.binnavi.Log.NaviLogger severe
严重: com.google.security.zynamics.binnavi.Importers.CImporterFactory.importIdbFileInternal(CImporterFactory.java:95)
com.google.security.zynamics.binnavi.Importers.CImporterFactory.access$000(CImporterFactory.java:44)
com.google.security.zynamics.binnavi.Importers.CImporterFactory$1.call(CImporterFactory.java:225)
com.google.security.zynamics.binnavi.Importers.CImporterFactory$1.call(CImporterFactory.java:221)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

**Comment by cblichmann** [comment]
Which version of IDA Pro are you using? BinNavi only supports IDA Pro up to 6.95 or the 7.0-x86compat version.
Did you set the IDA Pro installation directory when you set up BinNavi?

**Comment by DerZc** [comment]
I meet the same question and i use the IDA Pro 7.0, can you tell me how to solve it?

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
