### ISSUE TITLE
Xml external entity injection

### ISSUE THREAD

**Issue by 360CodeSafe** [google/binnavi#114]
RemoteFileSystem.java
![图片](https://user-images.githubusercontent.com/39950310/59007861-e744f100-885a-11e9-8836-8dd665383b97.png)
The xml external entity is not disabled when parsing the xml. When parsing the maliciously constructed data of the attacker, it will cause the xke attack.

**Comment by cblichmann** [comment]
I just pushed a fix for this, but the risk was very low to begin with: A malicious piece of code would have to compromise the debugger in order to inject anything into the data stream.
Then again, fixed is fixed, thanks for the report!
