### ISSUE TITLE
Ant buildfile location

### ISSUE THREAD

**Issue by bmihaila** [google/binnavi#15]
Hi

Why is the ant build file in ``src/main/java/com/google/security/zynamics/`` and not the toplevel directory? When importing the project into Eclipse it is automatically moved to the toplevel directory.
Executing it from there requires just two changes to path variables in the build file and works fine. The toplevel directory is the standard location anyway. So is there a reason not to have it in the toplevel directory?

**Comment by cblichmann** [comment]
Mostly for historical reasons; the code used to be structured differently. Agreed that we should move the file to its proper place. Care for another pull request? :)

**Comment by bmihaila** [comment]
Okay will test it again and then do a request.

**Comment by 0xFFFFFFFE** [comment]
:)

Bogdan Mihaila <notifications@github.com> schrieb am Mo., 31. Aug. 2015 um
11:01 Uhr:

**Comment by bmihaila** [comment]
@0xFFFFFFFE  Greets :)
