### ISSUE TITLE
Maven build

### ISSUE THREAD

**Issue by bmihaila** [google/binnavi#17]
Hi Christian

You mentioned in #13 that you are working on a Maven build. How is the status there? Playing around with the current file it seems that "main" builds just fine with maven but the tests don't even compile. 
So how is your progress there or are you giving up on that and we will stick to Gradle instead? I can help with Maven if you want to continue that or then lets concentrate on Gradle. Just would like to know where to put the energy in ;)

Bye
Bogdan

**Comment by cblichmann** [comment]
Hm, currently I'm slightly leaning towards getting rid of the Ant build file and to build everything with Maven. But that is only because I have exaclty zero knowledge of Gradle (apart from having heard that it is the new hot sh*t that replaced Ant as the default for Android).
I'll certainly merge the pull request for Gradle, but at least I won't be maintaining that. So IMO Maven should become the authoritative way to build BinNavi.
Right now, for the Maven build, I need to deal with the tests not compiling and packaging the final Jar file. After that we should be good and can remove the Ant file.

**Comment by bmihaila** [comment]
Getting rid of Ant is the goal anyway ;). About Gradle, well I don't have much experience there either but the syntax and flexibility looks good although like each build system it has its own pair of annoyances according to the internets.
Let me just tell you from years of Maven usage, Maven will sooner or later make you mad due to being too inflexible. My hope is that Gradle solves most of Maven's issues but who knows. Without experience I cannot tell ...

Then let's proceed with Maven for now and see how the Gradle build alternative comes along with the community. A later switch can still be done whenever Maven gets stuck and Gradle proves being able to handle the problem.

About packaging the Jar files. Have a look at the "maven-assembly-plugin". Although there are more of such plugins out there that at least worked for me to produce a "fat jar" with dependencies.

Bye
Bogdan

**Comment by cblichmann** [comment]
Yup, seen the "maven-assembly-plugin". That's what I was going to use :)
Agreed on the Gradle/Ant issue.

**Comment by lordqwerty** [comment]
Just to mention that a "fat jar" is being produced by Gradle as the default `gradle jar` build. This can be seen from line [77](https://github.com/google/binnavi/blob/master/build.gradle#L77) in [build.gradle](https://github.com/google/binnavi/blob/master/build.gradle) where it collects all of the Jars defined in the dependencies (lines [22 - 40](https://github.com/google/binnavi/blob/master/build.gradle#L22-L40)).

You might be interested in the [Maven Gradle Plugin](https://docs.gradle.org/current/userguide/maven_plugin.html) which will handle the deployment issues and such. I have little experience of this but would be happy to help. 

Cheers,
Jorden

**Comment by bmihaila** [comment]
Hi Jorden

Yes, Gradle seems nice, will definitely have a deeper look at it. Let's see how Eclipse works with it.
Keep up the work there then we non-Gradlers can learn from that :)

Bye
Bogdan

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
