### ISSUE TITLE
The database format is undocumented

### ISSUE THREAD

**Issue by thomasdullien** [google/binnavi#21]
At the moment, it is entirely unclear how a third-party disassembler should write to the database. This should be fixed to allow adding other disassemblers than IDA.

**Comment by thomasdullien** [comment]
I have begun writing a document that explains the format as good as I can, will polish it a bit more and then submit a pull request.

**Comment by bmihaila** [comment]
Hi Thomas

Great, more documentation on the internals is good.
However, I would like to know if writing to the database is the only way to interface Binnavi with a disassembler? Or put differently, if one would output REIL or native instruction objects from the disassembler (and basic blocks, functions etc.), is it currently easy to dump back these objects into the db? I see some classes in the ``database.postgresql`` package for writing back to the db but don't know how workable this idea is.
For me it currently seems easier to translate directly to REIL or native instruction objects than having to implement a database dumper for a given schema. So if there already exists something like a "cfg to db dumper" class, which would write out everything, I would prefer taking that route. Or am I missing something and disassembling directly to the db is the only possible way?

Bye
Bogdan

**Comment by thomasdullien** [comment]
Hey there,

so as far as I can tell, we have never "incrementally" updated the database - so I don't know if the stuff in the database.postgresql package can write back to the DB in it's current state. I agree though that this is quite desirable :-)

Anyhow, documenting both the format of the current DB dumper as well as the format of the DB that BinNavi converts the original dump to is required if we want to achieve direct-from-BinNavi-writing, I guess.

So to answer your question: We should build a CFG+CG to DB dumper eventually, but in order to do that, we'll have to document the DB format (both the one the IDA plugin writes to, as well as the one that BinNavi uses thereafter) much better.

Cheers,
Thomas
PS: Great to see you here :)

**Comment by cblichmann** [comment]
... also we're thinking about how to best open up the exporter plugin itself. Things will become a bit clearer then as well.

**Comment by bmihaila** [comment]
Feels good to be welcomed so warmly by you guys :). Hope I can keep up with the expectations.

But now back to the meat. So how I read your answer is that the db exporter I wanted is not-yet there or exists only in parts but that it would be good to have such a thing. Well, then I will start with some unit tests to see how complicated such a thing is. Meanwhile when the db format documentation is ready I can decide if front- or backdoor is the better interfacing strategy.

Bye
Bogdan

**Comment by thomasdullien** [comment]
Actually, perhaps it makes sense to build the documentation for the DB collaboratively. I have a doc I started, so I presume the way to work on this jointly would be to
- fork the BinNavi repo
- commit the work-in-process-doc into the fork
- work with others collaboratively on it
- "upstream" the doc into the main BinNavi repo when it's ready?

Sorry if this sounds daft, I am unsure what the best workflow for this is.

**Comment by cblichmann** [comment]
You can work on it in a separate branch, that's how the GitHub pages usually work (See gh_pages branch)

**Comment by bmihaila** [comment]
@thomasdullien 
I agree on the collaborative part but do not see any value in it being kept out of the main repo while not-yet-ready. People will want to read through it from the start and things never get "ready" anyways.

Just get things going and update on the go. Use a feature branch if needed like Christian suggests. Also you should use the issue tracker or the wiki for discussion and write the end results of discussions into the doc. This way everything happens in the open and people will be able to see "why" something turned out to be implemented in a certain way.

**Comment by bmihaila** [comment]
> ... also we're thinking about how to best open up the exporter plugin itself. Things will become a bit 
>  clearer then as well.

@cblichmann Depends on how long the opening takes ;). Did not sound like happening too soon.

But anyways, the exporter as far as I remember would only perform a translation/dump of IDA instruction trees to the Binnavi db. Am I right there? So one would then have to somehow build IDA data structures trees to be able to use the exporter to dump something to the database. 
Or did you mean the benefit would be to use the translator methods as the db writer from own code?

**Comment by 0xFFFFFFFE** [comment]
Just a little bit of information such that you guys can use all the information which is already available within the currently checked in code. The [postgresql_tables.sql]  (https://github.com/google/binnavi/blob/48891363d60b0d421e16c4c9aa8bd73f27b763d8/src/main/java/com/google/security/zynamics/binnavi/data/postgresql_tables.sql) file already has a lot of inline information about the (BinNavi) data base schema. Also there is an older python2sql exporter checked into the zynamics repository which documents the [Exporter](https://github.com/zynamics/ida2sql-plugin-ida/blob/master/ida_to_sql/sql_exporter.py) data base schema to some extend.

@bmihaila I also agree that this should be done within this repository. The history argument for all the whys makes the most sense for me as well.

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
