### ISSUE TITLE
REIL instruction source operands with different sizes

### ISSUE THREAD

**Issue by gitttt** [google/binnavi#22]
In the CSW’09 paper, see www.zynamics.com/downloads/csw09.pdf, the authors of REIL state:
„Right now there are no limitations on how operand sizes can be combined in one instruction.”

And indeed, in BinNavi you see REIL instructions such as:

or    [DWORD 0, BYTE t3, DWORD edx]

and [DWORD edx, BYTE 255, BYTE t1]

My question: What is the result of such arithmetic or bit-wise instructions where one source operand is smaller than the other? Is the smaller of the two source operands zero-extended or sign-extended before the operation is performed? Or does it depend on the instruction? Here is a third interesting example:

add [WORD 1, BYTE 255, WORD t0]"

Sign- or zero-extend?

I couldn't find any info on this in the specification although I _would guess_ it should be sign-extend here.

Thanks for the clarification!

**Comment by 0xFFFFFFFE** [comment]
The code / answer you are looking for can be found [here](https://github.com/google/binnavi/blob/master/src/main/java/com/google/security/zynamics/reil/interpreter/ReilInterpreter.java). As the code shows e.g for the OR instruction the result size is currently based on the third operand. This is only half the truth though, within the [monotone solver framework](https://github.com/google/binnavi/blob/master/src/main/java/com/google/security/zynamics/reil/algorithms/mono2/common/PerInstructionTransformationProvider.java) you can define your own semantics.
