### ISSUE TITLE
Replacing the IDA frontend dependency a.k.a. Uncle Dave wants YOU for Binnavi!

### ISSUE THREAD

**Issue by bmihaila** [google/binnavi#25]
Greetings, all Binnavi enthusiasts

Binnavi is now finally open source but it lacks an open disassembler frontend and a decompiler to be usable as a standalone reversing tool. Currently (the latest version of) IDA Pro is required to import a binary into Binnavi which is a huge limitation. It has always been.
Luckily, there are some people who want to solve this, some by throwing money at it: https://twitter.com/capstone_engine/status/634034005294215169 and others who want to throw conference tickets and Miami beaches: https://lists.immunityinc.com/pipermail/dailydave/2015-August/000987.html and São Paulo parties: https://lists.immunityinc.com/pipermail/dailydave/2015-August/000990.html at it.

They want YOU! So put your mouth where the money is! Let's use this momentum to solve the IDA issue.

I was planing to work on a disassembler frontend for Binnavi as I could reuse code from the Bindead project: https://bitbucket.org/mihaila/bindead/ but it will take some time to finish such a thing if done at least half-right. So with the current hype I figured that it is wiser to try to involve everybody (yeah, bikeshedding!) who wants to help with the design, coding or testing. 
Implementing a disassembler involves many tedious tasks and in this case we also need to implement the control flow reconstruction and a database writer so having many people working on it will speed up the process remarkably. But don't hesitate as most of the above already exists in parts but it still has to be put together and be brought to a usable state. The biggest argument though is that most good disassemblers and decompilers out there implement some heuristics and black art somewhere. That's what makes them good ones! Collecting this trickery in a wiki and trying to include it in Binnavi would make this project worth more than all that 1000 single tools out there. 

And remember Dave Aitel wants YOU for that!

---

Now to my proposal. Let's use this as a meta-issue for coordination and spin different issues from it for the subtopics and separate tasks. Next we could use the wiki to collect all the final decisions from the various upcoming discussions. That way people can have a look at the current status/consensus  without having to wade through lots of different discussion threads on the issue tracker.

Some ideas for the first steps. Let's brainstorm the currently existing free (and open) projects for each of the required components and collect these in the wiki. Next we need to decide how to interface existing or new code components with the current Binnavi API and any modifications that might be necessary in the latter.

Note however that before this leads to endless bikeshedding the imperative is that everyone can implement things their way if they disagree with something. There may coexist N disassemblers and M decompilers (plugins ftw!). None should be killed prematurely. The main intention here is to avoid a duplication of effort for all the problems that will come along the way. Further it should serve as documentation and as a knowledge base, i.e. the wiki.

I will describe my thoughts on the disassembler and existing work soon in a separate issue. See you there.

Bye,
Bogdan

**Comment by bmihaila** [comment]
As promised I wrote down my initial thoughts on potential disassemblers for Binnavi and what needs to be done in this #28 issue. Now I want some comments :smiley: 

Some less elaborate thoughts on decompilers will follow some other day.

Bye,
Bogdan

**Comment by 0xFFFFFFFE** [comment]
Awesome !

Bogdan Mihaila <notifications@github.com> schrieb am Do., 3. Sep. 2015 um
13:58 Uhr:

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
