### ISSUE TITLE
Musings on a disassembler frontend

### ISSUE THREAD

**Issue by bmihaila** [google/binnavi#28]
Hi

I promised to elaborate more on the disassemblers issue. Here come some ideas and requirements for disassemblers that could be used as a frontend in Binnavi.

Moved to the [Wiki](https://github.com/google/binnavi/wiki/Replacing-IDA-as-Disassembler-Frontend)

Ok, so far for my initial thoughts. Comments, additions and any corrections to the above are welcome and greatly appreciated.

---

My plan for now is to see how to interface Bindead with Binnavi but I am open for helping to interface any other of the existing disassemblers with Binnavi. Just need someone to step up and start the interfacing work with some other disassembler and convince me it is a better idea than working on Bindead :wink:.

Bye
Bogdan

**Comment by 0xFFFFFFFE** [comment]
There is also https://github.com/rose-compiler/rose as disassembler.

**Comment by bmihaila** [comment]
Just add some information about it here. We should get a wiki for that anyways.

**Comment by cblichmann** [comment]
Just my two cents for instruction decoding:
- Vanilla LLVM + custom TableGen to access the decoded instructions (= Capstone, but with proper C++-API)
- BeaEngine

**Comment by manizzle** [comment]
https://github.com/cseagle/fREedom 

Capstone to Binnavi ILL, though it seems to be a hacky disassembler. It might be better to use a disassembler that does CFG recovery already. 

Also this might be useful:
https://github.com/zynamics/ida2sql-plugin-ida

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
