### ISSUE TITLE
Opening up the Wiki

### ISSUE THREAD

**Issue by bmihaila** [google/binnavi#29]
Hi

How about opening up the wiki here on this project page. As described in my disassembler musings #28 it would be nice to collect ideas in a wiki. We can also use some markdown file in a `docs` folder but that would require pull-requests and will end up very slow. A wiki here would be much easier for people to participate. You can add there everything that is too big to go into the Readme file and to volatile to live in a `docs` directory.

What do you think?

Bye
Bogdan

**Comment by cblichmann** [comment]
Wiki enabled
