### ISSUE TITLE
Text to REIL Assembler

### ISSUE THREAD

**Issue by bmihaila** [google/binnavi#30]
Hi

Is there already an assembler for REIL? I am speaking of a parser of textual REIL that builds the according Java object hierarchy. Does that already exist?

It would be useful for a couple of things:
- for testing purposes to not have to instantiate all the objects in Java code and combine them by hand when writing tests
- for later modifications to an already disassembled CFG. You might want to see how a static analysis changes if you add/remove/modify instructions
- for a simple interface to Binnavi to quickly try out your disassembler. Although this interface is not scalable for disassembling huge binaries
  it would be the most simple interface to try out your own disassembler with Binnavi. For example Radare spits out REIL https://twitter.com/akochkov/status/634018147696250880
  and for other disassemblers it would be less effort to just write out some REIL assembler text file than interface with the DB

So what is your opinion on this? It should not be too complicated to implement one using a standard parser generator as REIL has only a handful of instructions and the format is quite simple and column based with `(address|label) mnemonic operand*`.  
We have an assembler in Bindead for RREIL and it really isn't so complicated but it was a huge help to implement unit tests and try out things as you do not have to go all the way through a C compiler and then disassembler to test something. Not to mention that compilers anyway optimize the code the way you sometimes do not want to. Of course one can use an x86 assembler and then a disassembler to achieve nearly the same but that already requires the disassembler ;). A text to REIL objects assembler would be nicer.

Bye
Bogdan

**Comment by cblichmann** [comment]
No objections from me here. Can you relicense the Bindead assembler to Apache2? In that case we could import that code here and work with it freely. If not, we can still import it into a sub-directory with a different license as long as it does not "link" with BinNavi. So in that case it might be better to maintain it in a separate repository.

**Comment by bmihaila** [comment]
Regarding the licensing.
I would have no problem in relicensing it, however there were more people involved so I might have to ask them. For the beginning I would also try to do it piecewise as dumping everything here would cause chaos :). Also revisiting and splitting up the functional parts as needed will do good to the Bindead codebase. 
So I would go the way of putting pieces into a subdirectory first and move other pieces/interfaces that link with Binnavi to the Binnavi directory. I guess that is easier than publishing things on Maven central and adding a dependency here. Also easier for people who want to fix something.

**Comment by bmihaila** [comment]
Now on the assembler issue. I wasn't meaning to use the one from Bindead but asking if there is already such a functionality in Binnavi and if not what you people think about implementing one. Like I said the REIL grammar isn't too complex and it would mean defining a parser and having a visitor plus a factory to spit out objects. So that would be written from scratch. If you feel it is useful.

**Comment by cblichmann** [comment]
No, we currently don't have any such functionality. If you want to, run with it. That's one of the reasons we opened it up, after all.

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
