### ISSUE TITLE
License issues and CLA

### ISSUE THREAD

**Issue by bmihaila** [google/binnavi#31]
What open source licenses are compatible with the Google CLA or is it possible at all to add e.g. GPL code to this repository? If each author has to agree on the CLA then the only alternative to include compatible open source code is to pack it as an external dependency I guess. This might get a little hairy if there are patches to external code that need to be applied before building.

What is your take on that?

Bye,
Bogdan

**Comment by cblichmann** [comment]
Disclaimer: I'm not a lawyer, so this is no legal advice.
I don't think we can generally add GPL'ed code to this repo. The license for BinNavi is Apache2 which is compatible with the more permissive end of the license spectrum (think 2-/3-clause BSD, MIT, etc.).
That said, GPL'ed code can IMO be added to a sub-directory, if any of the following is true
The code that's added
* is not an integral part of BinNavi,
* is one of several components which use the same interface or
* is a stand-alone work unrelated to BinNavi and just happens to be located in its repo.

**Comment by bmihaila** [comment]
Guess it should be then discussed on a case by case basis but sounds good to me from a non-lawyer to a non-lawyer :). 
My concrete example would have been the binary file format parsers (ELF, PE ...) code, which is based on code using the Eclipse public license.
Feel free to close this issue as I got my answer. Or then you can wait for a more authoritative lawyer answer :).

**Comment by cblichmann** [comment]
Note that the EPL is not compatible with the GPL (any version) unless the code is dual licensed. No idea about the interactions with the Apache license, though.
