### ISSUE TITLE
Add the source code for the IDA Pro plugins

### ISSUE THREAD

**Issue by cblichmann** [google/binnavi#32]
See title, the source code for the IDA Pro plugins is currently missing from BinNavi. For various Google-internal reasons, this was not released with the initial source drop.

**Comment by cblichmann** [comment]
Work on this will start 2015-09-21 and is expected to take a few weeks (as this is not my main project).

**Comment by bmihaila** [comment]
Thanks for giving an estimated time. That'll make lots of people happy.
How hard would it be then to backport the exporters to older IDA versions? I realized that the current exporters provided here as a blob are not compatible with IDA versions < 6.7 as you mentioned in #6 

My 6.6 version does not like them because of missing symbols. Although the goal is to get rid of IDA it would be helpful to have it to compare the disassembler output.

**Comment by 0xFFFFFFFE** [comment]
A day of work if you do not know the source.

Tim

Bogdan Mihaila <notifications@github.com> schrieb am Do., 3. Sep. 2015 um
15:43 Uhr:

**Comment by EKarpulevich** [comment]
Up!
Hello, what about source code for the IDA Pro plugins?
We really need them. We have a few problems with IDA results exporter and we need a source code to fix plugins.

**Comment by flyninja** [comment]
+1, and source code for dbg-client. It's not secret - present in standalone-installer, sync with git-repo please.

**Comment by 0xFFFFFFFE** [comment]
We have just not gotten around to do it. The debugger will be open source
as well.

Vitaly <notifications@github.com> schrieb am Di., 16. Feb. 2016 um
10:03 Uhr:

**Comment by EKarpulevich** [comment]
What about IDA plugin?
I've been waiting for it since October.

> cblichmann commented on Sep 3, 2015
> Work on this will start 2015-09-21 and is expected to take a few weeks (as this is not my main project).

**Comment by thomasdullien** [comment]
Hey there,

so I am not currently at Google, so I don't know about the internals, but I
wouldn't hold my breath for the
open-sourcing of the IDA plugins. The debug client, on the other hand,
should be relatively simple.

What's the problem you're trying to solve on the IDA plugin? Perhaps
there's a way to help w/o
having the source to the plugin.

Cheers,
Thomas

2016-02-16 10:22 GMT+01:00 EKarpulevich <notifications@github.com>:

**Comment by EKarpulevich** [comment]
Hello.
I need to export x86 chromium to binnavi database.
And I have bd_alloc error because of 2gb limit on x86.

x86-64 plugin can export x86-64 chromium, not x86. So we need to patch x86-64 plugin to export 32bit apps.

And anyway I need source code of plugin to future work.

**Comment by thomasdullien** [comment]
Hey,

cool thanks for the clarification. It's surprising that the 64bit plugin
doesn't oom, since iirc IDA is always a 32 bit process (even when
disassembling 64bit code). I presume you are exporting from Linux?

In all honesty, it may be worth to make a plan to get disassembly exports
w/o IDA, e.g. a full and scalable disasm outside of the 32-bit confines.
Chris Eagle had started something, but we'd need some more design & effort
to build something production - ready.

I will probably tackle the problem myself starting this November, but
that's probably too late for you. :-/

Cheers,
Thomas

**Comment by 0xFFFFFFFE** [comment]
Could you try setting the user mem limit in IDA higher?
http://www.zynamics.com/kb/kb0005.html

thomasdullien <notifications@github.com> schrieb am Di., 16. Feb. 2016 um
10:54 Uhr:

> Hey,
>
> cool thanks for the clarification. It's surprising that the 64bit plugin
> doesn't oom, since iirc IDA is always a 32 bit process (even when
> disassembling 64bit code). I presume you are exporting from Linux?
>
> In all honesty, it may be worth to make a plan to get disassembly exports
> w/o IDA, e.g. a full and scalable disasm outside of the 32-bit confines.
> Chris Eagle had started something, but we'd need some more design & effort
> to build something production - ready.
>
> I will probably tackle the problem myself starting this November, but
> that's probably too late for you. :-/
>
> Cheers,
> Thomas

**Comment by 0xFFFFFFFE** [comment]
Another factor here may be that you have more plugins installed in your IDA
32 bit version then in the 64 bit one. All of the plugins loaded will
consume memory resources. You could also try loading only the plugin you
need without the rest. (This is pushing it though :) )

Tim Kornau <tim.kornau@gmail.com> schrieb am Di., 16. Feb. 2016 um
10:58 Uhr:

> Could you try setting the user mem limit in IDA higher?
> http://www.zynamics.com/kb/kb0005.html
>
> thomasdullien <notifications@github.com> schrieb am Di., 16. Feb. 2016 um
> 10:54 Uhr:
>
>> Hey,
>>
>> cool thanks for the clarification. It's surprising that the 64bit plugin
>> doesn't oom, since iirc IDA is always a 32 bit process (even when
>> disassembling 64bit code). I presume you are exporting from Linux?
>>
>> In all honesty, it may be worth to make a plan to get disassembly exports
>> w/o IDA, e.g. a full and scalable disasm outside of the 32-bit confines.
>> Chris Eagle had started something, but we'd need some more design & effort
>> to build something production - ready.
>>
>> I will probably tackle the problem myself starting this November, but
>> that's probably too late for you. :-/
>>
>> Cheers,
>> Thomas

**Comment by cblichmann** [comment]
I just pushed the source code for the debug clients. It was always included in the Window Installer package anyways.

@thomasdullien @EKarpulevich: I am still working on getting the source code for zynamics_binexport_8 out of the door. For various internal (technical) reasons, this turned out to be a lot harder than expected.
Please be patient, this is not my main project :)

@0xFFFFFFFE: The 3GB split has been IDA's default since a few versions now. On Linux, this behavior is the default anyways.

**Comment by thomasdullien** [comment]
Cool, thanks a lot :-)

**Comment by 0xFFFFFFFE** [comment]
Yes this is the default now. Was the version used mentioned? OOM mentioned
to happen at 2GB.

thomasdullien <notifications@github.com> schrieb am Di., 16. Feb. 2016 um
11:40 Uhr:

**Comment by cblichmann** [comment]
Can't find the source for this, but it's been the default since at least late 2010.

**Comment by flyninja** [comment]
Thank for 88b222dcbcad222785bb7ec69ba573ba31983e61 (dbg-sources). What about #64? Do you synch plugin builds, or we are see plugin-sources? Builds full compatible with idasdk6.9?

**Comment by cblichmann** [comment]
Yes, the sources for the BinExport plugin will be made available and it will be compatible with IDA SDK 6.9. I'm working on getting it into releaseable shape. As for #64, I think we should just remove the files from the prebuilt folder, there is the GitHub release feature for these things anyways.

**Comment by flyninja** [comment]
C++ sources will be made with any build-automation?

**Comment by cblichmann** [comment]
Yes, via TravisCI/AppVeyor

**Comment by cblichmann** [comment]
This has now been published: https://github.com/google/binexport

Travis CI/AppVeyor to follow. Will upload binaries later.
