### ISSUE TITLE
E00060: The module could not be initialized

### ISSUE THREAD

**Issue by joxeankoret** [google/binnavi#62]
Hi, I'm unable to initialize any module after importing it. It always fails with the following message:

```
The module 'whatever' could not be initialized.

Possible causes:
  - There was a problem with the database connection.

Problem impact:
  - The module was not initialized.
```

The stack trace is the following one:

```
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:413)
com.google.security.zynamics.binnavi.Database.AbstractModuleCreator.initializeModule(AbstractModuleCreator.java:330)
com.google.security.zynamics.binnavi.Database.PostgreSQLProvider.initializeModule(PostgreSQLProvider.java:475)
com.google.security.zynamics.binnavi.disassembly.Modules.CModule.initialize(CModule.java:326)
com.google.security.zynamics.binnavi.Gui.MainWindow.Implementations.CModuleInitializationFunctions.initializeModuleInternal(CModuleInitializationFunctions.java:69)
com.google.security.zynamics.binnavi.Gui.MainWindow.Implementations.CModuleInitializationFunctions.access$000(CModuleInitializationFunctions.java:33)
com.google.security.zynamics.binnavi.Gui.MainWindow.Implementations.CModuleInitializationFunctions$2.run(CModuleInitializationFunctions.java:117)
```

I tried in both Linux x86, AMD64 and Windows 10 x86_64. The PostgreSQL server is 9.3 and the databases are created as UTF-8. Am I doing something wrong?

**Comment by joxeankoret** [comment]
Found the reason thanks to @thomasdullien . It seems that BinNavi is a bit sensitive to use databases not created with BinNavi itself, failing for unknown reasons. The workaround is to use it the way BinNavi expects. This is what Thomas told me how he usually initializes modules:

> 1) Right-click on the left-hand part of the main BinNavi window, "add
> database"
> 2) Fill in username / password / DB name
> 3) Click on "test connection"
> 4) Get the promt "The DB does not exist, do you want to create it"
> 5) Click yes
> 6) Double-click on the DB on the left to connect
> 7) Right-click on "modules" and click on "import IDB file"

Importing the IDB following these steps, initialization of modules works as expected. So, the problem is  related to how databases are created.

**Comment by DrMcCoy** [comment]
I did exactly that, let BinNavi create the DB itself, but I still get this error. Does that user need special superuser privileges, apart from CreateDB?

It would be really useful if BinNavi reported the actual error it received...

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.

**Comment by DrMcCoy** [comment]
Ah, yes, typical for Google... *shakes head*

**Comment by cblichmann** [comment]
Sorry for that. But for some rationale, please read the commit message for 14b6870158d69e698dc44ac70e405a243def3229.
