### ISSUE TITLE
Can't import any idb files

### ISSUE THREAD

**Issue by syjzwjj** [google/binnavi#63]
Hi~ I want to import idb files to binnavi And When I click import button

![qq20160125-0 2x](https://cloud.githubusercontent.com/assets/3119309/12544684/461c592c-c377-11e5-848b-b8d565b23048.png)

And the progress bar on the right corner appears.but when the progress bar finish . I can't see any modules in the database:

![qq20160125-1 2x](https://cloud.githubusercontent.com/assets/3119309/12544746/9e6ffa02-c377-11e5-9ddb-f5131297035e.png)

Why can't I import any idb files? And my binnavi files was builded from source,ida version is 6.8. Hope for the solution thanks!

**Comment by flyninja** [comment]
replace zynamics_binexport plugin from plugins-ida-dir to binnavi/prebuild binaries.

**Comment by syjzwjj** [comment]
Finaly I found this plugin cannot run on xp so I change a system and it work ! thanks

**Comment by cblichmann** [comment]
Good to hear :)
