### ISSUE TITLE
Error RAIL translator sbb

### ISSUE THREAD

**Issue by flyninja** [google/binnavi#64]
Trace:

```
Exception in thread "AWT-EventQueue-0"  at com.google.security.zynamics.binnavi.
API.disassembly.Function.getReilCode(Function.java:337)
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)

com.google.security.zynamics.binnavi.API.reil.InternalTranslationException: com.
google.security.zynamics.binnavi.API.reil.InternalTranslationException: com.goog
le.security.zynamics.reil.translators.InternalTranslationException: Error: The o
perands of SBB instructions must have equal size
```

One of next instructions:

```
opcode: 1B C2                       - sbb     eax, edx     
opcode: 1B B0 8C 01 00 00   - sbb     esi, [eax+18Ch]
opcode: 1B CF                       - sbb     ecx, edi
```

other sbb-instructions in the test function is not present

**Comment by 0xFFFFFFFE** [comment]
Hi Vitaly,

which exporter are you using. The current REIL translators are quite picky
about operand sizes, I suggest looking at the individual operand trees for
the three instructions in question and checking which one violates the
constraint. All of the operands should have a size of b4 as root node of
the individual operand trees.

Tim

Vitaly <notifications@github.com> schrieb am Di., 26. Jan. 2016 um
23:46 Uhr:

**Comment by flyninja** [comment]
To replay I use windows-installer from prebuild-dir as-is with export-plugin. You can reproduce bug using the instruction opcodes for the minimum sample?

**Comment by flyninja** [comment]
Sorry, Tim, I'am stupid... correctly pointed out the error and the method of reproduction. Error consistently reproduced using as the exporter of the plugin-file prebuild-directory size of 4550656 bytes. If you use the plugin is installed by the msi-installer, the size of 4208128 bytes, the error can not be played.
Instructions on which trips, I am also confused :).
Minimum case:
```cpp
//cl /c /Fotest.obj test.cpp
//link /debug /pdb:test.pdb test.obj
int rail(int a1)
{
	__asm
	{
		sbb     ecx, 0
	};

	return 0;
}

int main()
{
	return rail(2);
}
```
exporter code:

```python
def exporter():
    pi = StandAlone.getPluginInterface()
    dbm = pi.databaseManager
    dbm.addDatabase(...)       
    db = dbm.databases[0]
    try:
        db.connect()
        db.load() 
        
        print db
        
        for m in db.modules:
            print m.getName()
            if m.getName() != "test.exe" : continue
            try:
                m.load()
                for f in m.getFunctions():
                    if f.getName() != "rail(int)" : continue
                    try:
                        f.load()
                        print f.getName()
                        print f.getReilCode() #<<exc
                    finally:
                        f.close()
            finally:
                m.close()
    finally:
        db.close()
```

Please synchronize the files in the installer and git

**Comment by roninteger** [comment]
Hello, 

I just saw this error. It happens exactly the same to me but I do not understand how it is solved.

Exception in thread "AWT-EventQueue-0" at com.google.security.zynamics.binnavi.API.disassembly.Function.getReilCode(Function.java:337)
at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)

com.google.security.zynamics.binnavi.API.reil.InternalTranslationException: com.google.security.zynamics.binnavi.API.reil.InternalTranslationException: com.google.security.zynamics.reil.translators.InternalTranslationException: Error: The operands of SBB instructions must have equal size

thank'u

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
