### ISSUE TITLE
Broken Operand tracing functionality

### ISSUE THREAD

**Issue by KurSh** [google/binnavi#65]
Commit 9f4cf53 broke operand tracing functionality. 
We try to execute:
` m_workList = MinMaxPriorityQueue.expectedSize(m_graph.size()).create();`

But**_ m_graph.size()_** implemented in the  _**/binnavi/src/main/java/com/google/security/zynamics/reil/yfileswrap/algorithms/mono2/common/instructiongraph/CReilInstructionGraph.java**_, newer called and we have exception. Instead it called  a prebuilt wrapper.

Reverting commit solve problem, but how properly fix issue?

Trace:
`
Caused by: java.lang.AbstractMethodError: com.google.security.zynamics.reil.yfileswrap.algorithms.mono2.common.instructiongraph.CReilInstructionGraph.size()I
	at com.google.security.zynamics.reil.algorithms.mono2.common.MonoReilSolver.<init>(MonoReilSolver.java:77)
	at com.google.security.zynamics.reil.algorithms.mono2.registertracking.RegisterTracker.track(RegisterTracker.java:61)
	at com.google.security.zynamics.binnavi.Gui.GraphWindows.BottomPanel.RegisterTracker.CTracking.track(CTracking.java:66)
	at com.google.security.zynamics.binnavi.Gui.GraphWindows.BottomPanel.RegisterTracker.CTrackOperandAction.actionPerformed(CTrackOperandAction.java:88)
	... 44 more

`

Shamil

**Comment by thomasdullien** [comment]
Hey there,

The fix should be a recompile/rebuild/recommit of the obfuscated part of
the code. I have pinged someone to do it; we should try to automatically do
so in the future somehow.

Cheers,
Thomas

**Comment by 0xFFFFFFFE** [comment]
We should also get the tests for BinNavi running again. In this case they
could have caught this issue quite early.

thomasdullien <notifications@github.com> schrieb am Fr., 29. Jan. 2016 um
12:11 Uhr:

> Hey there,
>
> The fix should be a recompile/rebuild/recommit of the obfuscated part of
> the code. I have pinged someone to do it; we should try to automatically do
> so in the future somehow.
>
> Cheers,
> Thomas

**Comment by thomasdullien** [comment]
Hey there,

while I agree that getting the tests back is important I am not sure if the
issue would have been caught easily then.

If someone modifies files in the yfileswrap folder, and cannot regenerate
the obfuscated jar, the tests may likely continue to run against the
now-outdated obfuscated jar & pass. At least that's what I think happened
here.

**Comment by thomasdullien** [comment]
Hey there,

hmmm nevermind the test running onto the size() call should've failed.

In general, the dev process for people modifying yfileswrap is a bit
dangerous. If you have yfiles, you can easily end up making changes that
work locally (because you've rebuilt your yfileswrap) but break for others
(coz the rebuilt yfileswrap wasn't committed).

Cheers,
Thomas

**Comment by cblichmann** [comment]
TravisCI has support for builds with encrypted files. Those will only be accessible to the builder host and the GitHub account that is used for TravisCI.
