### ISSUE TITLE
Missed libraries for tests

### ISSUE THREAD

**Issue by grotrek** [google/binnavi#66]
We need some libraries to run the tests.
com.google.common.flags.Flags
com.google.common.logging.LogConfig
com.google.net.borg_bridge.ProxyLocator
com.google.net.borg_bridge.VirtualSocketImplFactory
Where we can obtain this libraries?

**Comment by grotrek** [comment]
Also some tests expect a certain version of Notepad, but there is no info which.

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
