### ISSUE TITLE
Adding a new architecture

### ISSUE THREAD

**Issue by lmolas-sadosky** [google/binnavi#67]
Hi, I wanted to know if it's possible to add a new architecture to BinNavi (hence a new REIL translator), and what would that entail, particularly regarding the BinNavi codebase structure.

For what I've seen in the code (following the [`ARM-32`][1] example), the translator should go in [`reil/translators`][2], and references to it in [`binnavi/REIL/CtranslatorFactory.java`][3] and [`reil/translators/ReilTranslator.java`][4] to be able to create an instance of the translator and use it. Also an entry should be added to [`binnavi/data/postgresql_tables.sql`][5] with the new `architecture_type`.

I haven't found much information on this issue, so I'm sure I'm missing a lot of details.

Thanks,
Lucas

[1]: https://github.com/google/binnavi/search?utf8=%E2%9C%93&q=arm-32
[2]: https://github.com/google/binnavi/tree/master/src/main/java/com/google/security/zynamics/reil/translators
[3]: https://github.com/google/binnavi/blob/master/src/main/java/com/google/security/zynamics/binnavi/REIL/CTranslatorFactory.java#L55
[4]: https://github.com/google/binnavi/blob/master/src/main/java/com/google/security/zynamics/reil/translators/ReilTranslator.java#L61
[5]: https://github.com/google/binnavi/blob/master/src/main/java/com/google/security/zynamics/binnavi/data/postgresql_tables.sql#L40

**Comment by lmolas-sadosky** [comment]
Hi again, reading a bit more, I realized that a new Importer for the architecture would also had to be added to the IDA Pro plugin. As I understand from issue #32, the source code for the plugin is not yet available, the closest I've found was Ero's [IDA2SQL plugin][1], but I don't think that's enough to get the job done.

I have an external disassembler for the target architecture, what would be the simplest (not the best) way to interface it with BinNavi (I mean I'm targeting a concrete interface for one architecture, not a generic solution like issue #25).

Reading the [wiki][2] written by @bmihaila about this, the first two proposals seem reasonable enough:

* Writing directly to the Binnavi database, issue #21 suggest it's not documented well enough, what's the current state of it?

* Perform the REIL translation separately and import that into BinNavi.

What would be the recommended way to go?

Thanks,
Lucas

[1]: https://github.com/zynamics/ida2sql-plugin-ida

[2]: https://github.com/google/binnavi/wiki/Replacing-IDA-as-Disassembler-Frontend#alternatives-for-interfacing-a-disassembler-with-binnavi

**Comment by thomasdullien** [comment]
Hey Lucas,

I am travelling with minimal connectivity, will try to answer as best as I
can in 2-3 days.

Did you see cseagles python - based x86 disassembler for binnavi? The best
way to interact with navi is writing the disassembly to the DB.

Cheers, and sorry for current brevity,
Thomas

**Comment by lmolas-sadosky** [comment]
Hi Thomas, thanks for this initial response. I'll study the [fREedom][1] project you mentioned, and how it interacts with the BinNavi database.

I was actually hoping the second option, importing already translated REIL code into BinNavi, would be possible. I'm a developer of the [BARF][2] project, a framework that provides the tools to perform a REIL translation of a defined architecture, and that way I wouldn't have to interact with the  BinNavi database, which as mentioned earlier, lacks a bit of documentation. But I'm not sure that even with the REIL code provided, BinNavi wouldn't still need to have the `ex_?_` tables populated.

Thanks,
Lucas

[1]: https://github.com/cseagle/fREedom
[2]: https://github.com/programa-stic/barf-project

**Comment by thomasdullien** [comment]
Hey there,

first off, sorry for the long delay. Perhaps I should first ask: What do you want to do with the REIL code in BinNavi once it is exported?

Normally, Navi translates on-demand, but there is nothing that would stop you from writing the REIL code to the database 'as if' it was a proper CPU - but I am not sure what useful things could be done from there ...

Cheers,
Thomas
PS: I should have more regular internet access over the next month and should reply more quickly :-)

**Comment by lmolas-sadosky** [comment]
The source code for the IDA Pro plugin exporter into BinNavi has been published, as another GitHub repo: [binexport][1]. This greatly simplifies the interaction with the BinNavi database.


[1]: https://github.com/google/binexport
