### ISSUE TITLE
No IDA pro plugin for Mac OS X

### ISSUE THREAD

**Issue by pkuzhangchao** [google/binnavi#7]
After successfully build and run BinNavi on Mac OS X, it cannot install the plugins for IDA Pro.

1) The file browser dialog cannot open the directory /Applications/IDAPro/iadq.app
2) Even if I remove the postfix .app from the path, and make it browse the directory  /Applications/IDAPro/idaq/Contents/MacOS/,  and then try to install the plugins. It fails. It puts two empty files zynamics_binexport_8.pmc and zynamics_binexport_8.pmc64 in the sub-directory plugins/. I cannot find any plugins for OS X in the codebase, rather than plugins for Linux and Windows.

**Comment by zTrix** [comment]
It seems that only windows and linux plugins provided, zynamics_binexport_8.pmc and zynamics_binexport_8.pmc64 are not provided in this repo.

Hope google will release them soon.

**Comment by 0xFFFFFFFE** [comment]
We currently have no build setup for OSX, we acknowledge that this is not optimal. I file this as a feature request.

**Comment by nihilus** [comment]
@0xFFFFFFFE Can't you distribute the old zynamics_binexport_6.pmc and zynamics_binexport_6.pmc64 until further?

**Comment by cblichmann** [comment]
@nihilus Those no longer work with recent versions of BinNavi, unfortunately.

**Comment by 0xFFFFFFFE** [comment]
@nihilus Christian is right. The old exporter did not have support for the type system and other changes we did while the migration from mysql to postgresql was in progress. The currently best option is to use some form of VM to export into the DB. I know this is not really nice, but as I stated we are working on getting this out at some point. I "just" have to find time to setup the OSX build env.

**Comment by nihilus** [comment]
0xFFFFFFFE: what is the reason to keeping the exporter plugin as closed source?

**Comment by cblichmann** [comment]
It's mostly organizational and practical issues. There is quite some code shared with and internal version that we can't/won't release that's difficult to separate without downright forking it. After all, we still want to be able to make changes to both parts without too much effort.
Expect some movement in this regard in the coming weeks (with an unspecified number of weeks :)).

**Comment by 0xFFFFFFFE** [comment]
+1 on what @cblichmann said. 
Additional our internal argument also involves some form of fear / risk associated with releasing the code. To understand what is happening here, the exporter is a full blown disassembler on its own. It has control flow reconstruction, instruction decoding, entry point, ... to massage IDA output into out desired format. 
The current plan we are trying to follow is to separate the database logic from the rest of the code in a nice way such that it reduces the pain to understand what to write where when and in which order.

**Comment by jaouahbi** [comment]
It would be incredibly useful for those who work with mac. Thanks

**Comment by cblichmann** [comment]
BinExport source code is now also on GitHub: https://github.com/google/binexport
It can be built for Linux, Windows and Mac OS X.
