### ISSUE TITLE
x64 translator support

### ISSUE THREAD

**Issue by grotrek** [google/binnavi#76]
Hello. We want to implement a support of x64 translation to REIL code. We have already done some work and want to create PR. Does this PR destination will be master branch or you create new one? Are there any other recommendations?

**Comment by cblichmann** [comment]
I think it's best if you create a feature branch for this, say "reil-x64". I suppose you'll be working on this for some time, so having a feature/topic branch makes it easier to sync with master (= upstream).
In general, some things should already work with 64-bit, but we really haven't put much effort into that yet. Just be mindful of Java's limited ability to do proper 64-bit arithmetic :-)

**Comment by thomasdullien** [comment]
Hey there,

it may also be worth looking at the following two projects:

https://github.com/c01db33f/reil
https://github.com/Cr4sh/openreil

I think a lot of the 64-bit work may already have been done there, we'd
just need to figure
out a good way to combine things.

Cheers,
Thomas

2016-03-18 23:35 GMT+08:00 Christian Blichmann <notifications@github.com>:

**Comment by gitttt** [comment]
Careful, the reil of the two above mentioned reil may not be compatible to the binnavi reil emulator. By the time these projetcts started binnavi was closed source and the reil emulator was not public.

**Comment by grotrek** [comment]
I need prepared "reil-x64" branch to create PR to it. May you create it for me?

**Comment by ASD-VR** [comment]
Hi grotrek,

We are also working on a x64 translator, but it looks like your ahead of us. When you do your PR lets work out a division of labour.

**Comment by 0xFFFFFFFE** [comment]
I added the requested branch.

**Comment by grotrek** [comment]
I added pr #88

**Comment by grotrek** [comment]
What should we do to you merge reil-x64 branch to master?

**Comment by Manouchehri** [comment]
Pinging for an update as well, #88 hasn't gotten into master yet.

**Comment by grotrek** [comment]
@cblichmann @0xFFFFFFFE What should we do to you merge reil-x64 branch to master? Any comment?

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
