### ISSUE TITLE
using a self-created postgresql database leads to java.lang.NullPointerException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by gitttt** [google/binnavi#8]
It seems you currently cannot use addDatabase(...) in a stand-alone script if you do not have previously created a database via the BinNavi Gui (e.g. the first time you run BinNavi).

I created a database via 
sudo -u postgres psql postgres -c "CREATE DATABASE \"new_database\""

but this led to 
  File "test.py", line 41, in init_binnavi
    db.connect()
    at java.io.Reader.<init>(Reader.java:78)
    at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
    at com.google.security.zynamics.binnavi.Database.AbstractSQLProvider.parseSystemResourceAsSQLFile(SourceFile:240)
    at com.google.security.zynamics.binnavi.Database.AbstractSQLProvider.createEmptyTables(SourceFile:415)
    at com.google.security.zynamics.binnavi.Database.PostgreSQLProvider.initializeDatabase(SourceFile:453)
    at com.google.security.zynamics.binnavi.Database.CDatabaseConnection.connect(SourceFile:73)
    at com.google.security.zynamics.binnavi.Database.CDatabase.connect(SourceFile:273)
    at com.google.security.zynamics.binnavi.API.disassembly.Database.connect(SourceFile:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

java.lang.NullPointerException: java.lang.NullPointerException

NB: not creating any database led to the error "FATAL: database "new_database" does not exist", which is a correct behavior. So BinNavi notices when I create a database via the terminal but it seems to have problems using it. I compared the terminal-created database with the gui-created one but could not find any differences (e.g. Name, Owner, Encoding, ...)

**Comment by cblichmann** [comment]
I'm having trouble matching your line numbers to the current source, did you change it much? Also, can you provide the relevant parts of the script you're using?

**Comment by gitttt** [comment]
Oh, sorry. I am not using the github version but a previous one.
Maybe it is a better idea if I describe what I would like to do:

I would like to use BinNavi via a stand-alone script, without ever running the BinNavi Gui.
Currently I have to run the BinNavi gui at least once to create a postgresql database.

If I do not create the database via the Gui (the initial screen you see when you run BinNavi), then doing a addDatabase, for example like this:

pi = StandAlone.getPluginInterface()
    
# For stand-alone scripts, the BinNavi configuration file is not read, therefore the
# database that stores all data must be set up manually.
dbm = pi.databaseManager
    
dbm.addDatabase(
        "database_description",  # database description
        "org.postgresql.Driver", # database driver
        "localhost",             # database host
        "new_database",          # database name
        "postgres",              # database user
        "password",              # database password
        "Max Mustermann",        # collaboration name
        False,                   # save password
        False)                   # auto connect

db = dbm.databases[0]
db.connect()

leads to the error 

"FATAL: database "new_database" does not exist".


So my question:
How can I create this database?

BTW: The BinNavi support told me some weeks ago that there is currently no way to create the database via the API but that I have to create it myself. They pointed me to the initialize function found here: https://github.com/google/binnavi/blob/bc69529530a6f229e904a72a5c73653a5c3c70a0/src/main/java/com/google/security/zynamics/binnavi/Gui/Database/implementations/CDatabaseConnector.java

**Comment by 0xFFFFFFFE** [comment]
Thanks for the report. We will take a look at this issue.

**Comment by gitttt** [comment]
Any news on this?

**Comment by 0xFFFFFFFE** [comment]
I am on vacation back Monday.
Am 24.09.2015 6:12 nachm. schrieb "gitttt" <notifications@github.com>:

**Comment by thomasdullien** [comment]
I may be able to look into it this weekend. Is it theoretically possible that it's a classpath issue?

If you look at
https://github.com/google/binnavi/blob/fd9b2c58fed9694e22430664dee3bfee9f3da609/src/main/java/com/google/security/zynamics/binnavi/Database/AbstractSQLProvider.java
it seems that the code tries to read a file - can you check if this is what's going on in the meantime?

Cheers,
Thomas

**Comment by 0xFFFFFFFE** [comment]
Cool that would be great.
Am 24.09.2015 7:30 nachm. schrieb "thomasdullien" <notifications@github.com

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
