### ISSUE TITLE
Building BinNavi with OpenJDK 7?

### ISSUE THREAD

**Issue by tkchia** [google/binnavi#81]
Good day,

May I know if BinNavi should be buildable (and runnable) under OpenJDK 7?  I am currently not able to get the code to build under this JDK, and I understand that the testing for BinNavi is done with Oracle JDK 8.

Specifically, I installed maven (3.0.5-1) and openjdk-7-jdk (7u95-2.6.4-0ubuntu0.14.04.2) on Ubuntu 14.04.4 LTS, and followed the instructions in README.md to build BinNavi (revision 0b9f663d57c7), and I encountered error messages in the Ant step, like so:

    $ ant build-binnavi-fat-jar
    Buildfile: .../binnavi/build.xml
    
    clean:
    
    build-revision:
    
    build-zylib-jar:
        [mkdir] Created dir: .../binnavi/target/classes
        [javac] Compiling 375 source files to .../binnavi/target/classes
        [javac] .../binnavi/src/main/java/com/google/security/zynamics/zylib/general/PairHelpers.java:38: error: ')' expected
        [javac]             .map(Pair::first)
        [javac]                      ^
        [javac] .../binnavi/src/main/java/com/google/security/zynamics/zylib/general/PairHelpers.java:38: error: illegal start of expression
        [javac]             .map(Pair::first)
        [javac]                       ^
        [javac] .../binnavi/src/main/java/com/google/security/zynamics/zylib/general/PairHelpers.java:38: error: ';' expected
        [javac]             .map(Pair::first)
        [javac]                             ^
        [javac] .../binnavi/src/main/java/com/google/security/zynamics/zylib/general/PairHelpers.java:54: error: ')' expected
        [javac]             .map(Pair::second)
        [javac]                      ^
        [javac] .../binnavi/src/main/java/com/google/security/zynamics/zylib/general/PairHelpers.java:54: error: illegal start of expression
        [javac]             .map(Pair::second)
        [javac]                       ^
        [javac] .../binnavi/src/main/java/com/google/security/zynamics/zylib/general/PairHelpers.java:54: error: ';' expected
        [javac]             .map(Pair::second)
        [javac]                              ^
        [javac] 6 errors

Thank you for any advice!

**Comment by ssherei** [comment]
I had this issue before, using the official Oracle-jdk fixed it for me. 

Regards,
Saif

**Comment by tkchia** [comment]
Thanks. I finally got around the problem (I think) by installing a package for OpenJDK *8* on my Ubuntu 14.04 box. I had to add in the `openjdk-r/ppa` PPA to do so:

    sudo add-apt-repository ppa:openjdk-r/ppa
    sudo apt-get update
    sudo apt-get install openjdk-8-jdk
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    ...
    mvn dependency:copy-dependencies
    ant build-binnavi-fat-jar

I got a few warning messages saying that

        [javac] Note: Some input files use or override a deprecated API.
        [javac] Note: Recompile with -Xlint:deprecation for details.

but otherwise the build was successful.

Thank you!
