### ISSUE TITLE
How to get the type of operands?

### ISSUE THREAD

**Issue by meteorlxy** [google/binnavi#85]
Hello. I'm a beginner of BinNavi and IDA. I want to get the type of the operands like the IDC function `GetOpType()` does, but I only find something like the optype in the table `ex_1_expression_nodes`.
Is the optype information saved in the database? Or I have to determine the type by the combination of the nodes in the table `ex_1_expression_nodes` by myself?

**Comment by gitttt** [comment]
@meteorlxy Any news on this?

**Comment by thomasdullien** [comment]
Hey there,

are you writing a Java plugin or are you writing Jython code? From the
Jython API
there should be a way to get the instruction and then the entire operand
tree directly;
I think there's a similar API in the Java part of the code. Can you provide
more details
about what you're doing?

Cheers,
Thomas

2016-10-15 9:13 GMT+02:00 gitttt <notifications@github.com>:

**Comment by meteorlxy** [comment]
@thomasdullien   
Sorry for my late reply.  

I was doing my gradution project that day. My project is about software plagiarism detection. I was trying to extract some properties from a software. I think the optype could be a useful property.  
I was writing Java, and I read the data from Pgsql DB via JDBC. So I wondered how to get the operands' type from  the tables.

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
