### ISSUE TITLE
Consistent IllegalArgumentException on .i64 Module Load

### ISSUE THREAD

**Issue by noperand** [google/binnavi#90]
Using a build of BinNavi 6.1 @ 0e17596 (also reproduced with the latest release build), I encounter an exception that prevents the loading of x64 IDBs while everything works fine with x86 IDBs. I'm using IDA Pro Version 6.9.160222 (64-bit), PostgreSQL 9.5.3, and BinExport 9 @ a0efa77.

This is quickly reproducible using calc.exe to perform a test on Windows 8.1 x64. Starting from scratch, I create a simple PostgreSQL superuser ('binnavi') and configure a new database connection in BinNavi. After successfully testing the database connection, BinNavi creates the database since it does not exist. I then import the IDB (calc.i64) and initialize the module -- no problem. When I subsequently attempt to load the module, I encounter the following exception and the module tabs remain disabled:

```
INFO: <42>    <16 ms>    select id, name, description from bn_traces join bn_module_traces on bn_module_traces.trace_id = bn_traces.id where bn_module_traces.module_id = 1
Exception in thread "Thread-14" java.lang.IllegalArgumentException: Error: the offset of the type instance is not within section boundaries.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.security.zynamics.binnavi.disassembly.types.TypeInstance.<init> TypeInstance.java:81)
        at com.google.security.zynamics.binnavi.disassembly.types.TypeInstanceContainerBackend.loadTypeInstances(TypeInstanceContainerBackend.java:444)
        at com.google.security.zynamics.binnavi.disassembly.types.TypeInstanceContainer.initialize(TypeInstanceContainer.java:450)
        at com.google.security.zynamics.binnavi.disassembly.Modules.CModule.load(CModule.java:494)
        at com.google.security.zynamics.binnavi.Gui.Loaders.CModuleLoader.loadModuleInternal(CModuleLoader.java:72)
        at com.google.security.zynamics.binnavi.Gui.Loaders.CModuleLoader.access$000(CModuleLoader.java:43)
        at com.google.security.zynamics.binnavi.Gui.Loaders.CModuleLoader$2.run(CModuleLoader.java:126)
```

Parallel import configuration has no effect, I get no further detail after maximizing log verbosity, and I can consistently reproduce this exception after dropping the database through psql and going through the steps again. Any ideas on why this might occur? It's quite odd that it only occurs with x64 IDBs (.i64's).

Thanks in advance.

**Comment by noperand** [comment]
Woops. In my haste, I didn't notice that x64 isn't quite supported yet.

**Comment by noperand** [comment]
I spent some more time on this and decided to reopen the issue. This isn't failing due to a lack of support for x64. This is failing due to an abundance of section_offsets going beyond the referenced section boundaries for TypeInstances after initializing imported .i64s. Here is some Python to gather more information on why the precondition check is failing, leading to the IllegalArgumentException:

```
#!/usr/bin/env python

import sys
import psycopg2
import psycopg2.extras

def find_section(sections, lookup_id):
    """Simple section lookup by id."""
    for s in sections:
        if s['id'] == lookup_id:
            return s

# Check all persisted TypeInstances to identify violations of the assertion on
# TypeInstance load.
# (line 81 of src\main\java\com\google\security\zynamics\binnavi\disassembly\types\TypeInstance.java).
if __name__ == "__main__":
    conn_string = "host='localhost' dbname='binnavi' user='binnavi' password='Testing123$'"
    conn = psycopg2.connect(conn_string)
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    
    # Fetch all current initialized sections
    cursor.execute("SELECT * FROM bn_sections")
    sections = cursor.fetchall()
    
    # Fetch all current TypeInstances
    cursor.execute("SELECT * FROM bn_type_instances")
    type_instances = cursor.fetchall()
    
    # Compare and tally up bad TypeInstances
    bad_type_instance_count = 0
    for t in type_instances:
        s = find_section(sections, t['section_id']) # lookup the section for this TypeInstance
        if (s['start_address'] + t['section_offset']) > s['end_address']: # does section_offset put us outside of the section?
            bad_type_instance_count += 1
            #print t
    
    print "Out of %d TypeInstances, %d use section_offsets that put us outside the referenced section." % (len(type_instances), bad_type_instance_count)
    sys.exit(0)
```
In my testing, I'm finding that the x86 .IDBs I initialize do not end up with section_offsets outside of the referenced section. I'm finding that this happens *a lot* with .i64's. The Python code above finds no offenders prior to the first attempted initialization of the only module in the BinNavi database. This is the output I get after importing and initializing calc.i64:

> Out of 647 TypeInstances, 459 use section_offsets that put us outside the referenced section.

Any ideas why this might be occurring? I will continue to investigate as time allows and contribute what I find.

**Comment by gitttt** [comment]
You write 

> I didn't notice that x64 isn't quite supported yet.

Does this x64 refer to the target executable to be analyzed, or to the operating system (or java sdk (?)) that binnavi run on?

In other words, can Binnavi analyze 32bit executables on a 64bit Linux? If yes, do I have to install a 32bit or 64bit Java?

**Comment by 0xFFFFFFFE** [comment]
As platform where the Java VM runs on all architectures that Java support will (should) run BinNavi fine. From a perspective of support for analysis of x64 support is not complete and also not close to it.

**Comment by norandom** [comment]
I also see this a lot, for ELF x86_64

Is there a fix?

**Comment by thomasdullien** [comment]
I hope to be able to look into this mid-next week.

**Comment by cblichmann** [comment]
The BinNavi project is no longer under active development.
