### ISSUE TITLE
Wiki Outdated.

### ISSUE THREAD

**Issue by Manouchehri** [google/binnavi#92]
Shouldn't [`Replacing IDA as Disassembler Frontend`](https://github.com/google/binnavi/wiki/) point to [BinExport](https://github.com/google/binexport) now?

**Comment by thomasdullien** [comment]
Not quite - BinExport does not really replace IDA, only allows to export from it?

Anyhow, I will look into it :-)

**Comment by Manouchehri** [comment]
Using the BinExport protobuffers format seems to be far easier than what the Wiki is suggesting, unless I'm misunderstanding something (which is very possible).

Last week I tried reading in a `.BinExport` file (created from IDA) from Python and it looked straightforward. https://gist.github.com/Manouchehri/80ca41f22e94026c9910f58966f276f9

**Comment by cblichmann** [comment]
@Manouchehri, I take it you've seen https://github.com/google/binexport/blob/master/tools/binexport2dump.cc? This is basically how you "reassemble" a text representation of the disassembly stored in .BinExport while still keeping all the useful extra information.

**Comment by Manouchehri** [comment]
Indeed I have. =) 

I opened up a discussion at https://github.com/google/binexport/issues/14 to avoid cluttering BinNavi with BinExport questions.

**Comment by Manouchehri** [comment]
@0xFFFFFFFE The wiki doesn't mention BinExport, not sure if I follow why this was closed?
