### ISSUE TITLE
function BinExport2Diff8 undefined

### ISSUE THREAD

**Issue by morsisko** [google/binnavi#93]
What steps will reproduce the problem?
1.Diff 2 .idb

What is the expected output? What do you see instead?

Difference between 2 binary
Error : function BinExport2Diff8 undefined

What version of the product are you using? On what operating system?

Bindiff 4.2
IDA Pro 6.6
Windows 7 64bits
Java 8

Inside IDA console:

```
LoadLibrary(C:\Program Files (x86)\IDA\plugins\python.plw) error: Can't find procedure

C:\Program Files (x86)\IDA\plugins\python.plw: can't load file

LoadLibrary(C:\Program Files (x86)\IDA\plugins\zynamics_bindiff_4_2.plw) error: Can't find procedure

C:\Program Files (x86)\IDA\plugins\zynamics_bindiff_4_2.plw: can't load file

LoadLibrary(C:\Program Files (x86)\IDA\plugins\zynamics_binexport_8.plw) error: Can't find procedure
C:\Program Files (x86)\IDA\plugins\zynamics_binexport_8.plw: can't load file
```

Above files are in the location.

**Comment by cblichmann** [comment]
Hi there,

You're reporting an issue with BinDiff, not BinNavi.
Please note that IDA 6.6 is no longer supported. We only support IDA Pro 6.8 or higher, sorry.

Christian

**Comment by shooshx** [comment]
I'm seeing this exact error message with IDA 6.8 as well. Any possible fix for this?

**Comment by cblichmann** [comment]
Hmm, I can't test right now, but maybe I was mistaken with the exact IDA version it should work with. Do you have access to 6.95 or 7.0 (x86_compat)?
If you use Dependency Walker on `zynamics_binexport_8.plw` or `zynamics_bindiff_4_2.plw` you can see which symbol is the culprit.

**Comment by TestItOnlyOnce** [comment]
There are requests to functions that exist only in Windows Vista+, so there is that too. IDA 6.8 works on Windows XP but those plugins are not:
For zynamics_bindiff_4_2.plw:
```
InitializeSRWLock
ReleaseSRWLockShared
AcquireSRWLockShared
ReleaseSRWLockExclusive
AcquireSRWLockExclusive
WakeAllConditionVariable
SleepConditionVariableSRW
```
And for zynamics_binexport_9.plw:
```
GetLocaleInfoEx
```

**Comment by cblichmann** [comment]
Hi there! Thanks for your comment. If you want to file an issue for BinDiff, please use https://bugs.zynamics.com/bindiff
Also note that we're preparing for a BinDiff 5.0 release that natively supports IDA 7, so no new development is being done for 4.2/4.3 and IDA <= 6.95.
