### ISSUE TITLE
E00043: IDB file could not be imported

### ISSUE THREAD

**Issue by xinghuacai** [google/binnavi#94]
The IDB file 'C:\Users\klionsec7\Documents\Visual Studio 2015\Projects\consolewhetherSEH\consolewhetherSEH\Debug\vc140.idb' could not be imported. Please check the stack trace for more information.

Possible causes:
  - Database connection problems.
  - Bug in the IDB exporter.

Problem impact:
  - The IDB file was imported partially. A raw module in an incosistent state was created. This raw module should be deleted.

upon are the error information from binnavi,would you help me to find out the reason and solution?
(my system is win7(x64) and I am sure there is no problem on database connection)

**Comment by cblichmann** [comment]
You omitted the stack trace :-(
Also, which version/branch are you using? Are you using 6.1 with BinExport 9? Does this happen for all IDBs?

**Comment by xinghuacai** [comment]
stack trace：

com.google.security.zynamics.binnavi.Importers.CImporterFactory.importIdbFileInternal(CImporterFactory.java:98)
com.google.security.zynamics.binnavi.Importers.CImporterFactory.access$000(CImporterFactory.java:44)
com.google.security.zynamics.binnavi.Importers.CImporterFactory$1.call(CImporterFactory.java:225)
com.google.security.zynamics.binnavi.Importers.CImporterFactory$1.call(CImporterFactory.java:221)
java.util.concurrent.FutureTask.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)

I am using 6.1 with binexport9,this happen for all idbs
I copied those two plugin files(zynamics_binexport_9.p64,zynamics_binexport_9.plw) to my ida pro's plugin  directory

**Comment by cblichmann** [comment]
IDA version?
Also, did you click "Test Connection" to verify that you can talk to the database server?
Does a binary export from IDA work (Edit|Plugins|BinExport 9, then "BinExport v2 Binary Export")?

**Comment by xinghuacai** [comment]
I clicked "test connection" and vefified I can talk to the database server.
my ida version is 6.6(6.8 tried too)
my (edit|plugins) does not work,and I can not see BinExport 9:),my ida pro is not a paid version,and it is expired for paid license.

**Comment by cblichmann** [comment]
We only support IDA Pro 6.8 or higher, so your 6.6 won't work. Please use 6.8 and check whether the BinExport 9 plugin gets loaded properly in that version. Once that works, don't forget to set 6.8 as the IDA version in BinNavi.

**Comment by xinghuacai** [comment]
when I tried to make idapro6.8 as the ida version in BinNavi,and restart my system,it fails again,but this time,my ida pro's Edit|Plugins has something(not blank),but still can not find Edit|Plugins|BinExport 9,should I install a new ida pro?if I download the latest version from ida pro's official website,but it's not paid for license,can I succeed?

**Comment by cblichmann** [comment]
(No need to restart your system)
BinExport will not work with the free version of IDA. You need the commerical (paid for) version of IDA Pro, sorry.

**Comment by bryongloden** [comment]
👍

**Comment by xinghuacai** [comment]
I tried to change the two files(zynamics_binexport_9.p64,zynamics_binexport_9.plw) to (zynamics_binexport_8.p64,zynamics_binexport_8.plw),and it worked on ida pro to see Edit|Plugin|BinExport8,but again when I turn back to binnavi,below errors come out:

E00041: Could not install BinExport
BinNavi could not install the BinExport because one of more files could not be copied.

Possible causes:
  - Insufficient rights to write to the IDA Pro directory
  - Some kind of IO problem occurred

Problem impact:
  - BinExport was not installed and can not be used to export IDB files to the database. You can try to install BinExport manually by copying the exporters/BinExport directory from your BinNavi installation to the IDA Pro directory.



java.io.FileOutputStream.open0(Native Method)
java.io.FileOutputStream.open(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
java.io.FileOutputStream.<init>(Unknown Source)
com.google.security.zynamics.binnavi.Gui.IdaSelectionDialog.CBinExportInstaller.copyFile(CBinExportInstaller.java:55)
com.google.security.zynamics.binnavi.Gui.IdaSelectionDialog.CBinExportInstaller.install(CBinExportInstaller.java:98)
com.google.security.zynamics.binnavi.Gui.IdaSelectionDialog.CBinExportInstaller.install(CBinExportInstaller.java:111)
com.google.security.zynamics.binnavi.Gui.IdaSelectionDialog.CIdaSelectionDialog$CppInstallerAction.actionPerformed(CIdaSelectionDialog.java:239)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.WaitDispatchSupport$2.run(Unknown Source)
java.awt.WaitDispatchSupport$4.run(Unknown Source)
java.awt.WaitDispatchSupport$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.awt.WaitDispatchSupport.enter(Unknown Source)
java.awt.Dialog.show(Unknown Source)
java.awt.Component.show(Unknown Source)
java.awt.Component.setVisible(Unknown Source)
java.awt.Window.setVisible(Unknown Source)
java.awt.Dialog.setVisible(Unknown Source)
com.google.security.zynamics.binnavi.Gui.IdaSelectionDialog.CIdaSelectionDialog.show(CIdaSelectionDialog.java:157)
com.google.security.zynamics.binnavi.Gui.SettingsDialog.CActionProvider.selectIDADirectory(CActionProvider.java:53)
com.google.security.zynamics.binnavi.Gui.SettingsDialog.CGeneralSettingsPanel$InternalIDAListener.actionPerformed(CGeneralSettingsPanel.java:212)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.WaitDispatchSupport$2.run(Unknown Source)
java.awt.WaitDispatchSupport$4.run(Unknown Source)
java.awt.WaitDispatchSupport$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.awt.WaitDispatchSupport.enter(Unknown Source)
java.awt.Dialog.show(Unknown Source)
java.awt.Component.show(Unknown Source)
java.awt.Component.setVisible(Unknown Source)
java.awt.Window.setVisible(Unknown Source)
java.awt.Dialog.setVisible(Unknown Source)
com.google.security.zynamics.binnavi.Gui.MainWindow.Implementations.CSettingsDialogFunctions.showSettingsDialog(CSettingsDialogFunctions.java:82)
com.google.security.zynamics.binnavi.Gui.MainWindow.ProjectTree.Actions.CActionShowSettingsDialog.actionPerformed(CActionShowSettingsDialog.java:58)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.AbstractButton.doClick(Unknown Source)
javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

would you please help me to find why ?

**Comment by xinghuacai** [comment]
I deal with it by using administrator privilege to open binnavi,and install binexport ida plugin sucessfully,
but when I turn back to import idb file,it seems good to work on importing idb files,but after clicking "import" key after I have choosed my idb files,nothing come out then,and I can not see the effect of importing idb files.

**Comment by xinghuacai** [comment]
I have another question,what should I do with Edit|Plugin|BinExport,should I use this BinExport function in my ida pro to export a file which will be imported to binnavi？

**Comment by xinghuacai** [comment]
finally I trid to install binnavi on windows 2003,and install ida pro6.8 on windows 2003(with BinExport9),
both BinExport9 in ida pro and binnavi in my win2003 succeed!
