### ISSUE TITLE
problem with the memory size 

### ISSUE THREAD

**Issue by xinghuacai** [google/binnavi#95]
can you help me:
when i installed my binnavi in win2003x32 ,since binnavi started,it remminds of a messagebox with below message:
"you are using binnavi with less than recommended 512 MB of memory. please check binnavi.bat in your binnavi directory to find out how to increase the available memory"

I can not find the binnavi.bat:(,I installed binnavi by download the binnavi-all.jar from the release link,
and don't know how to increase the availabel memory like the message told me to

**Comment by Manouchehri** [comment]
See https://github.com/google/binnavi/blob/master/src/main/java/com/google/security/zynamics/binnavi/data/binnavi.bat.

**Comment by cblichmann** [comment]
Yes that error message simply assumes BinNavi was installed using the Windows Installer package. @Manouchehri had the right idea :)
