### ISSUE TITLE
HiDPI Scaling

### ISSUE THREAD

**Issue by Manouchehri** [google/binnavi#96]
Swing doesn't handle scaling very well. Probably no easy fix.

![image](https://cloud.githubusercontent.com/assets/7232674/16350566/8ad88342-3a2d-11e6-9c0b-c729c4a6d109.png)

![image](https://cloud.githubusercontent.com/assets/7232674/16350600/b4564402-3a2d-11e6-954a-1ea7e16324b1.png)

**Comment by cblichmann** [comment]
Java 8 has no good support for HiDPI on Windows. Try if adding `-Dsun.java2d.dpiaware=true` to the BinNavi command-line works for you.
If this doesn't work, try using a recent Java 9 build, it should work there.

**Comment by Manouchehri** [comment]
Launching with `java -Dsun.java2d.dpiaware=true -Xms512m -Xmx4096m -jar C:\Users\David\nsadropbox\binnavi-all.jar` sadly doesn't seem to change anything (that I noticed anyway).

Using JRE 9 worked perfectly, thanks! http://openjdk.java.net/jeps/263

![image](https://cloud.githubusercontent.com/assets/7232674/16396763/5aba85f8-3c8e-11e6-9659-f13f1e15da74.png)

```cmd
C:\Users\David>"C:\Program Files\Java\jre-9\bin\java.exe" -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+124)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+124, mixed mode)
```

**Comment by Manouchehri** [comment]
Want me to add a note about HiDPI on Windows in README.md?

**Comment by thomasdullien** [comment]
Yes, that'd be great!

2016-06-27 23:52 GMT+02:00 David Manouchehri <notifications@github.com>:

**Comment by Manouchehri** [comment]
Done.
